### ISSUE TITLE
Create google folder of mockups

### ISSUE THREAD

**Issue by hmasha** [de-souza-capstone-2020/Mars#11]
Move mock ups and other screenshots from slack to google drive folder

**Comment by itsDZhang** [comment]
@hmasha 
What do you mean by this? 
Do you mean we create a google folder of mock-ups including @aasyedab 's video?

**Comment by itsDZhang** [comment]
@de-souza-capstone-2020/development 

Mock ups have been moved to google drive folder: https://drive.google.com/drive/u/0/folders/1DtxQNI1lHq8Gmks4akxfkpAiItjiWGZm

Closing issue.
