### ISSUE TITLE
Delete Previous Quick Replies

### ISSUE THREAD

**Issue by mllemango** [de-souza-capstone-2020/Mars#51]
### Description of Task
When the user selects from quick replies options, all options should disappear, preventing the user from re-selecting previous quick replies.

### Expected Behavior Upon Completion
Quick replies can only be selected once. 
They should be congregated at the bottom of the chat log for selection

**Comment by hmasha** [comment]
This might be helpful as to how to think about restructuring.

https://github.com/FaridSafi/react-native-gifted-chat/issues/367
