### ISSUE TITLE
Mock out Sleep Diary Entry Form

### ISSUE THREAD

**Issue by mllemango** [de-souza-capstone-2020/Mars#61]
### Description of Task
Create mock of sleep diary form including:
what types of questions to ask
how the questions will be answered (date picker vs clock module etc)
Find the best React Native components for the form

### Expected Behavior Upon Completion
A visual of the sleep diary entry form
A list of required libraries

**Comment by aasyedab** [comment]
![Sleep Diary qns   classifications](https://user-images.githubusercontent.com/43472966/72860357-8c9ac100-3c94-11ea-8e04-92cb40bbe4a5.jpeg)
Useful Reference Links: 
**Red** 
https://github.com/henninghall/react-native-date-picker/blob/master/README.md   https://facebook.github.io/react-native/docs/datepickerios w/out Date
**Green** 
https://github.com/henninghall/react-native-date-picker/blob/master/README.md  OR 
https://facebook.github.io/react-native/docs/datepickeriosw/out date & am/pm 
**Violet** 
https://facebook.github.io/react-native/docs/datepickerios
**Blue & Purple** 
https://snack.expo.io/@liscott327/react-native-picker-select---example
